### ISSUE TITLE
Stylesheet a JS script using fetch_class and fetch_method

### ISSUE THREAD

**Issue by wagnerfillio** [domProjects/CI-AdminLTE_4#1]
How to include stylesheet and JS script using fetch_class and fetch_method in this CI-adminlte_4, since in CI-adminlte we used footer.php?

Example:
```
<?php if ($this->router->fetch_class() == 'users' && ($this->router->fetch_method() == 'create' OR $this->router->fetch_method() == 'edit')): ?>
        <script src="<?php echo base_url($plugins_dir . '/pwstrength/pwstrength.min.js'); ?>"></script>
<?php endif; ?>
```

**Comment by domProjects** [comment]
Hi @wagnerfillio,

In the file **footer_scripts.php** (`application\views\backend\_template`), you can insert the code below:

```
if ($this->router->fetch_class() == 'users' && ($this->router->fetch_method() == 'create' OR $this->router->fetch_method() == 'edit'))
{
	echo '<script src="' . base_url($this->config->item('assets_backend') . '/pwstrength/pwstrength.min.js') . '"></script>';
}
```

I tested and it works ;)

**Comment by wagnerfillio** [comment]
Hi @domProjects,

It's working, thank you!!

**Comment by wagnerfillio** [comment]
Hello!

Can you help me with this?

Is it possible to leave a submenu active, even though this is a method of
another controller?

Example:



​

2018-03-01 14:55 GMT-03:00 Emmanuel Campait <notifications@github.com>:
